import "./globals.css";

import type { Metadata, Viewport } from "next";
import {
  Fira_Code,
  Geist,
  Geist_Mono,
  Lilita_One,
  Pacifico,
} from "next/font/google";

import BreakpointDebuggerWrapper from "@/app/components/BreakpointDebuggerWrapper";
import { InitTheme } from "@/app/components/InitTheme";
import { ThemeProvider } from "@/app/context/ThemeContext";
import { UIProvider } from "@/app/context/UIContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lilitaOne = Lilita_One({
  variable: "--font-lilita-one",
  subsets: ["latin"],
  weight: "400",
});

const firaCode = Fira_Code({
  subsets: ["latin"],
  variable: "--font-code",
});

const pacificoFont = Pacifico({
  subsets: ["latin"],
  variable: "--font-pacifico",
  weight: "400",
});

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-theme="dark"
      className="transition-colors duration-500 height-100 overflow-y-scroll overscroll-none scrollbar-hide"
    >
      <body
        className={`${lilitaOne.variable} ${geistMono.variable}
         ${firaCode.variable} ${pacificoFont.variable} antialiased`}
      >
        <ThemeProvider>
          <UIProvider>
            <main className="relative flex items-center justify-center ">
              {children}
            </main>
          </UIProvider>
        </ThemeProvider>
        <BreakpointDebuggerWrapper />
      </body>
    </html>
  );
}
