export const timelineTechnologies = {
  auvsi: [
    "Next.js",
    "Node.js",
    "TypeScript",
    "Prisma ORM",
    "AWS Cognito",
    "AWS RDS",
    "AWS S3",
    "AWS Lambda",
    "Python",
    "Flask",
    "React",
    "Tailwind CSS",
    "Framer Motion",
    "shadcn/ui",
    "Docker",
    "Kubernetes",
    "Vercel",
    "Google Cloud",
    "LangChain",
    "InstructLab",
    "Jupyter",
  ],
  oracleWebIntern: [
    "React",
    "Next.js",
    "Node.js",
    "Quarkus",
    "Oracle Cloud Infrastructure (OCI)",
    "Express",
    "Flask",
    "Tailwind CSS",
    "Framer Motion",
    "shadcn/ui",
    "Vercel",
    "Docker",
    "Google Cloud",
    "AWS",
  ],
  oracleCloudIntern: [
    "Oracle Kubernetes",
    "Oracle Docker",
    "Oracle Cloud Infrastructure (OCI)",
    "APEX",
    "CI/CD",
    "Container Orchestration",
    "Metrics Dashboards",
    "Automated Recovery Policies",
  ],
  blackLake: [
    "React",
    "Tailwind CSS",
    "JavaScript",
    "Ruby",
    "Inventory Systems",
    "Custom Reservation System",
  ],
  feral: [
    "JavaScript",
    "Ruby",
    "Backend Integration",
    "Reservations",
    "Inventory Management",
  ],
};
