export const timelineTechnologies = {
  vectal: [
    "Next.js 15",
    "React 19",
    "TypeScript",
    "Tailwind CSS",
    "Framer Motion",
    "shadcn/ui",
    "OpenAI API",
    "Anthropic",
    "Gemini",
    "OpenRouter",
    "LangChain",
    "Vector Databases",
    "Node.js",
    "FastAPI",
    "SQLAlchemy",
    "PostgreSQL",
    "Supabase",
    "PostHog",
    "Logfire",
    "Zeplo",
    "Vercel",
    "Render",
    "AWS",
    "Docker",
  ],
  auvsi: [
    "Next.js",
    "Node.js",
    "TypeScript",
    "Prisma ORM",
    "AWS Cognito",
    "AWS RDS",
    "AWS S3",
    "AWS Lambda",
    "Python",
    "Flask",
    "React",
    "Tailwind CSS",
    "Framer Motion",
    "shadcn/ui",
    "Docker",
    "Kubernetes",
    "Vercel",
    "Google Cloud",
    "LangChain",
    "InstructLab",
    "Jupyter",
  ],
  oracleWebIntern: [
    "React",
    "Next.js",
    "Node.js",
    "Quarkus",
    "Oracle Cloud Infrastructure (OCI)",
    "Express",
    "Flask",
    "Tailwind CSS",
    "Framer Motion",
    "shadcn/ui",
    "Vercel",
    "Docker",
    "Google Cloud",
    "AWS",
  ],
  oracleCloudIntern: [
    "Oracle Kubernetes",
    "Oracle Docker",
    "Oracle Cloud Infrastructure (OCI)",
    "APEX",
    "CI/CD",
    "Container Orchestration",
    "Metrics Dashboards",
    "Automated Recovery Policies",
  ],
  blackLake: [
    "React",
    "JavaScript",
    "TypeScript",
    "Tailwind CSS",
    "Ruby on Rails",
    "PostgreSQL",
    "Redis",
    "REST APIs",
    "AWS S3",
    "Heroku",
    "Git",
    "Inventory Systems",
    "Custom Reservation System",
  ],
  feral: [
    "React",
    "JavaScript",
    "Node.js",
    "Express",
    "Ruby on Rails",
    "PostgreSQL",
    "MongoDB",
    "REST APIs",
    "HTML/CSS",
    "SASS",
    "Git",
    "Heroku",
    "Stripe API",
  ],
};
